using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArtnetEmu
{
    public class Constants
    {
        public sealed class Windows
        {
            public const int WM_USER = 0x0400;
            public const int WM_COPYDATA = 0x004A;
            public const int WM_COMMAND = 0x0111;
            public const int PROCESS_VM_READ = 0x0010;
        }
        public sealed class Winamp
        {
            public const int IPC_GETVERSION = 0;
            public const int IPC_GETVERSIONSTRING = 1;
            public const int IPC_GETREGISTEREDVERSION = 770;
            public const int IPC_PLAYFILE = 100;  // dont be fooled, this is really the same as enqueufile
            public const int IPC_ENQUEUEFILE = 100;
            public const int IPC_PLAYFILEW = 1100;
            public const int IPC_ENQUEUEFILEW = 1100;
            public const int IPC_DELETE = 101;
            public const int IPC_DELETE_INT = 1101;
            public const int IPC_STARTPLAY = 102;
            public const int IPC_STARTPLAY_INT = 1102; // dont use, it's not fun
            public const int IPC_CHDIR = 103;
            public const int IPC_ISPLAYING = 104;
            public const int IPC_GETOUTPUTTIME = 105;
            public const int IPC_JUMPTOTIME = 106;
            public const int IPC_GETMODULENAME = 109;
            public const int IPC_EX_ISRIGHTEXE = 666;
            public const int IPC_WRITEPLAYLIST = 120;
            public const int IPC_SETPLAYLISTPOS = 121;
            public const int IPC_SETVOLUME = 122; // IPC_GETVOLUME: SendMessage(hwnd_winamp,WM_WA_IPC,-666,IPC_SETVOLUME)
            public const int IPC_SETPANNING = 123;
            public const int IPC_GETLISTLENGTH = 124;
            public const int IPC_GETLISTPOS = 125;
            public const int IPC_GETINFO = 126;
            public const int IPC_GETEQDATA = 127;
            public const int IPC_SETEQDATA = 128;
            public const int IPC_ADDBOOKMARK = 129;
            public const int IPC_ADDBOOKMARKW = 131;
            public const int IPC_INSTALLPLUGIN = 130;
            public const int IPC_RESTARTWINAMP = 135;
            public const int IPC_ISFULLSTOP = 400;
            public const int IPC_INETAVAILABLE = 242;
            public const int IPC_UPDTITLE = 243;
            public const int IPC_REFRESHPLCACHE = 247;
            public const int IPC_GET_SHUFFLE = 250;
            public const int IPC_GET_REPEAT = 251;
            public const int IPC_SET_SHUFFLE = 252;
            public const int IPC_SET_REPEAT = 253;
            public const int IPC_ENABLEDISABLE_ALL_WINDOWS = 259; // 0xdeadbeef to disable
            public const int IPC_GETWND = 260;
            public const int IPC_ISWNDVISIBLE = 261; // same param as IPC_GETWND
            // use one of these for the param
            public const int IPC_GETWND_EQ = 0;
            public const int IPC_GETWND_PE = 1;
            public const int IPC_GETWND_MB = 2;
            public const int IPC_GETWND_VIDEO = 3;

            // external commands. use with WM_COMMAND
            public const int WINAMP_FILE_QUIT = 40001;
            public const int WINAMP_OPTIONS_PREFS = 40012; // pops up the preferences
            public const int WINAMP_OPTIONS_AOT = 40019; // toggles always on top
            public const int WINAMP_FILE_REPEAT = 40022;
            public const int WINAMP_FILE_SHUFFLE = 40023;
            public const int WINAMP_HIGH_PRIORITY = 40025;
            public const int WINAMP_FILE_PLAY = 40029; // pops up the load file(s) box
            public const int WINAMP_OPTIONS_EQ = 40036; // toggles the EQ window
            public const int WINAMP_OPTIONS_ELAPSED = 40037;
            public const int WINAMP_OPTIONS_REMAINING = 40038;
            public const int WINAMP_OPTIONS_PLEDIT = 40040; // toggles the playlist window
            public const int WINAMP_HELP_ABOUT = 40041; // pops up the about box :)
            public const int WINAMP_MAINMENU = 40043;
            public const int WINAMP_BUTTON1 = 40044;
            public const int WINAMP_BUTTON2 = 40045;
            public const int WINAMP_BUTTON3 = 40046;
            public const int WINAMP_BUTTON4 = 40047;
            public const int WINAMP_BUTTON5 = 40048;
            public const int WINAMP_BUTTON1_SHIFT = 40144;
            public const int WINAMP_BUTTON2_SHIFT = 40145;
            public const int WINAMP_BUTTON3_SHIFT = 40146;
            public const int WINAMP_BUTTON4_SHIFT = 40147;
            public const int WINAMP_BUTTON5_SHIFT = 40148;
            public const int WINAMP_BUTTON1_CTRL = 40154;
            public const int WINAMP_BUTTON2_CTRL = 40155;
            public const int WINAMP_BUTTON3_CTRL = 40156;
            public const int WINAMP_BUTTON4_CTRL = 40157;
            public const int WINAMP_BUTTON5_CTRL = 40158;
            public const int WINAMP_VOLUMEUP = 40058; // turns the volume up a little
            public const int WINAMP_VOLUMEDOWN = 40059; // turns the volume down a little
            public const int WINAMP_FFWD5S = 40060; // fast forwards 5 seconds
            public const int WINAMP_REW5S = 40061; // rewinds 5 seconds
            public const int WINAMP_NEXT_WINDOW = 40063;
            public const int WINAMP_OPTIONS_WINDOWSHADE = 40064;
            public const int WINAMP_OPTIONS_DSIZE = 40165;
            public const int IDC_SORT_FILENAME = 40166;
            public const int IDC_SORT_FILETITLE = 40167;
            public const int IDC_SORT_ENTIREFILENAME = 40168;
            public const int IDC_SELECTALL = 40169;
            public const int IDC_SELECTNONE = 40170;
            public const int IDC_SELECTINV = 40171;
            public const int IDM_EQ_LOADPRE = 40172;
            public const int IDM_EQ_LOADMP3 = 40173;
            public const int IDM_EQ_LOADDEFAULT = 40174;
            public const int IDM_EQ_SAVEPRE = 40175;
            public const int IDM_EQ_SAVEMP3 = 40176;
            public const int IDM_EQ_SAVEDEFAULT = 40177;
            public const int IDM_EQ_DELPRE = 40178;
            public const int IDM_EQ_DELMP3 = 40180;
            public const int IDC_PLAYLIST_PLAY = 40184;
            public const int WINAMP_FILE_LOC = 40185;
            public const int WINAMP_OPTIONS_EASYMOVE = 40186;
            public const int WINAMP_FILE_DIR = 40187; // pops up the load directory box
            public const int WINAMP_EDIT_ID3 = 40188;
            public const int WINAMP_TOGGLE_AUTOSCROLL = 40189;
            public const int WINAMP_VISSETUP = 40190;
            public const int WINAMP_PLGSETUP = 40191;
            public const int WINAMP_VISPLUGIN = 40192;
            public const int WINAMP_JUMP = 40193;
            public const int WINAMP_JUMPFILE = 40194;
            public const int WINAMP_JUMP10FWD = 40195;
            public const int WINAMP_JUMP10BACK = 40197;
            public const int WINAMP_PREVSONG = 40198;
            public const int WINAMP_OPTIONS_EXTRAHQ = 40200;
            public const int ID_PE_NEW = 40201;
            public const int ID_PE_OPEN = 40202;
            public const int ID_PE_SAVE = 40203;
            public const int ID_PE_SAVEAS = 40204;
            public const int ID_PE_SELECTALL = 40205;
            public const int ID_PE_INVERT = 40206;
            public const int ID_PE_NONE = 40207;
            public const int ID_PE_ID3 = 40208;
            public const int ID_PE_S_TITLE = 40209;
            public const int ID_PE_S_FILENAME = 40210;
            public const int ID_PE_S_PATH = 40211;
            public const int ID_PE_S_RANDOM = 40212;
            public const int ID_PE_S_REV = 40213;
            public const int ID_PE_CLEAR = 40214;
            public const int ID_PE_MOVEUP = 40215;
            public const int ID_PE_MOVEDOWN = 40216;
            public const int WINAMP_SELSKIN = 40219;
            public const int WINAMP_VISCONF = 40221;
            public const int ID_PE_NONEXIST = 40222;
            public const int ID_PE_DELETEFROMDISK = 40223;
            public const int ID_PE_CLOSE = 40224;
            public const int WINAMP_VIS_SETOSC = 40226;
            public const int WINAMP_VIS_SETANA = 40227;
            public const int WINAMP_VIS_SETOFF = 40228;
            public const int WINAMP_VIS_DOTSCOPE = 40229;
            public const int WINAMP_VIS_LINESCOPE = 40230;
            public const int WINAMP_VIS_SOLIDSCOPE = 40231;
            public const int WINAMP_VIS_NORMANA = 40233;
            public const int WINAMP_VIS_FIREANA = 40234;
            public const int WINAMP_VIS_LINEANA = 40235;
            public const int WINAMP_VIS_NORMVU = 40236;
            public const int WINAMP_VIS_SMOOTHVU = 40237;
            public const int WINAMP_VIS_FULLREF = 40238;
            public const int WINAMP_VIS_FULLREF2 = 40239;
            public const int WINAMP_VIS_FULLREF3 = 40240;
            public const int WINAMP_VIS_FULLREF4 = 40241;
            public const int WINAMP_OPTIONS_TOGTIME = 40242;
            public const int EQ_ENABLE = 40244;
            public const int EQ_AUTO = 40245;
            public const int EQ_PRESETS = 40246;
            public const int WINAMP_VIS_FALLOFF0 = 40247;
            public const int WINAMP_VIS_FALLOFF1 = 40248;
            public const int WINAMP_VIS_FALLOFF2 = 40249;
            public const int WINAMP_VIS_FALLOFF3 = 40250;
            public const int WINAMP_VIS_FALLOFF4 = 40251;
            public const int WINAMP_VIS_PEAKS = 40252;
            public const int ID_LOAD_EQF = 40253;
            public const int ID_SAVE_EQF = 40254;
            public const int ID_PE_ENTRY = 40255;
            public const int ID_PE_SCROLLUP = 40256;
            public const int ID_PE_SCROLLDOWN = 40257;
            public const int WINAMP_MAIN_WINDOW = 40258;
            public const int WINAMP_VIS_PFALLOFF0 = 40259;
            public const int WINAMP_VIS_PFALLOFF1 = 40260;
            public const int WINAMP_VIS_PFALLOFF2 = 40261;
            public const int WINAMP_VIS_PFALLOFF3 = 40262;
            public const int WINAMP_VIS_PFALLOFF4 = 40263;
            public const int ID_PE_TOP = 40264;
            public const int ID_PE_BOTTOM = 40265;
            public const int WINAMP_OPTIONS_WINDOWSHADE_PL = 40266;
            public const int EQ_INC1 = 40267;
            public const int EQ_INC2 = 40268;
            public const int EQ_INC3 = 40269;
            public const int EQ_INC4 = 40270;
            public const int EQ_INC5 = 40271;
            public const int EQ_INC6 = 40272;
            public const int EQ_INC7 = 40273;
            public const int EQ_INC8 = 40274;
            public const int EQ_INC9 = 40275;
            public const int EQ_INC10 = 40276;
            public const int EQ_INCPRE = 40277;
            public const int EQ_DECPRE = 40278;
            public const int EQ_DEC1 = 40279;
            public const int EQ_DEC2 = 40280;
            public const int EQ_DEC3 = 40281;
            public const int EQ_DEC4 = 40282;
            public const int EQ_DEC5 = 40283;
            public const int EQ_DEC6 = 40284;
            public const int EQ_DEC7 = 40285;
            public const int EQ_DEC8 = 40286;
            public const int EQ_DEC9 = 40287;
            public const int EQ_DEC10 = 40288;
            public const int ID_PE_SCUP = 40289;
            public const int ID_PE_SCDOWN = 40290;
            public const int WINAMP_REFRESHSKIN = 40291;
            public const int ID_PE_PRINT = 40292;
            public const int ID_PE_EXTINFO = 40293;
            public const int WINAMP_PLAYLIST_ADVANCE = 40294;
            public const int WINAMP_VIS_LIN = 40295;
            public const int WINAMP_VIS_BAR = 40296;
            public const int WINAMP_OPTIONS_MINIBROWSER = 40298;
            public const int MB_FWD = 40299;
            public const int MB_BACK = 40300;
            public const int MB_RELOAD = 40301;
            public const int MB_OPENMENU = 40302;
            public const int MB_OPENLOC = 40303;
            public const int WINAMP_NEW_INSTANCE = 40305;
            public const int MB_UPDATE = 40309;
            public const int WINAMP_OPTIONS_WINDOWSHADE_EQ = 40310;
            public const int EQ_PANLEFT = 40313;
            public const int EQ_PANRIGHT = 40314;
            public const int WINAMP_GETMORESKINS = 40316;
            public const int WINAMP_VIS_OPTIONS = 40317;
            public const int WINAMP_PE_SEARCH = 40318;
            public const int ID_PE_BOOKMARK = 40319;
            public const int WINAMP_EDIT_BOOKMARKS = 40320;
            public const int WINAMP_MAKECURBOOKMARK = 40321;
            public const int ID_MAIN_PLAY_BOOKMARK_NONE = 40322;
            public const int ID_MAIN_PLAY_AUDIOCD = 40323; // starts playing the audio CD in the first CD reader
            public const int ID_MAIN_PLAY_AUDIOCD2 = 40324; // plays the 2nd
            public const int ID_MAIN_PLAY_AUDIOCD3 = 40325; // plays the 3rd
            public const int ID_MAIN_PLAY_AUDIOCD4 = 40326; // plays the 4th
            public const int WINAMP_OPTIONS_VIDEO = 40328;
            public const int ID_VIDEOWND_ZOOMFULLSCREEN = 40329;
            public const int ID_VIDEOWND_ZOOM100 = 40330;
            public const int ID_VIDEOWND_ZOOM200 = 40331;
            public const int ID_VIDEOWND_ZOOM50 = 40332;
            public const int ID_VIDEOWND_VIDEOOPTIONS = 40333;
            public const int WINAMP_MINIMIZE = 40334;
            public const int ID_PE_FONTBIGGER = 40335;
            public const int ID_PE_FONTSMALLER = 40336;
            public const int WINAMP_VIDEO_TOGGLE_FS = 40337;
            public const int WINAMP_VIDEO_TVBUTTON = 40338;
            public const int WINAMP_LIGHTNING_CLICK = 40339;
            public const int ID_FILE_ADDTOLIBRARY = 40344;
            public const int ID_HELP_HELPTOPICS = 40347;
            public const int ID_HELP_GETTINGSTARTED = 40348;
            public const int ID_HELP_WINAMPFORUMS = 40349;
            public const int ID_PLAY_VOLUMEUP = 40351;
            public const int ID_PLAY_VOLUMEDOWN = 40352;
            public const int ID_PEFILE_OPENPLAYLISTFROMLIBRARY_NOPLAYLISTSINLIBRARY = 40355;
            public const int ID_PEFILE_ADDFROMLIBRARY = 40356;
            public const int ID_PEFILE_CLOSEPLAYLISTEDITOR = 40357;
            public const int ID_PEPLAYLIST_PLAYLISTPREFERENCES = 40358;
            public const int ID_MLFILE_NEWPLAYLIST = 40359;
            public const int ID_MLFILE_LOADPLAYLIST = 40360;
            public const int ID_MLFILE_SAVEPLAYLIST = 40361;
            public const int ID_MLFILE_ADDMEDIATOLIBRARY = 40362;
            public const int ID_MLFILE_CLOSEMEDIALIBRARY = 40363;
            public const int ID_MLVIEW_NOWPLAYING = 40364;
            public const int ID_MLVIEW_LOCALMEDIA_ALLMEDIA = 40366;
            public const int ID_MLVIEW_LOCALMEDIA_AUDIO = 40367;
            public const int ID_MLVIEW_LOCALMEDIA_VIDEO = 40368;
            public const int ID_MLVIEW_PLAYLISTS_NOPLAYLISTINLIBRARY = 40369;
            public const int ID_MLVIEW_INTERNETRADIO = 40370;
            public const int ID_MLVIEW_INTERNETTV = 40371;
            public const int ID_MLVIEW_LIBRARYPREFERENCES = 40372;
            public const int ID_MLVIEW_DEVICES_NOAVAILABLEDEVICE = 40373;
            public const int ID_MLFILE_IMPORTCURRENTPLAYLIST = 40374;
            public const int ID_MLVIEW_MEDIA = 40376;
            public const int ID_MLVIEW_PLAYLISTS = 40377;
            public const int ID_MLVIEW_MEDIA_ALLMEDIA = 40377;
            public const int ID_MLVIEW_DEVICES = 40378;
            public const int ID_FILE_SHOWLIBRARY = 40379;
            public const int ID_FILE_CLOSELIBRARY = 40380;
            public const int ID_POST_PLAY_PLAYLIST = 40381;
            public const int ID_VIS_NEXT = 40382;
            public const int ID_VIS_PREV = 40383;
            public const int ID_VIS_RANDOM = 40384;
            public const int ID_MANAGEPLAYLISTS = 40385;
            public const int ID_PREFS_SKIN_SWITCHTOSKIN = 40386;
            public const int ID_PREFS_SKIN_DELETESKIN = 40387;
            public const int ID_PREFS_SKIN_RENAMESKIN = 40388;
            public const int ID_VIS_FS = 40389;
            public const int ID_VIS_CFG = 40390;
            public const int ID_VIS_MENU = 40391;
            public const int ID_VIS_SET_FS_FLAG = 40392;
            public const int ID_PE_SHOWPLAYING = 40393;
            public const int ID_HELP_REGISTERWINAMPPRO = 40394;
            public const int ID_PE_MANUAL_ADVANCE = 40395;
            public const int ID_SWITCH_COLOURTHEME = 44500;
            public const int ID_GENFF_LIMIT = 45000;

            /*
            // Only available for plugins
            public const int IPC_SETSKINW = 199;
            public const int IPC_SETSKIN = 200;
            public const int IPC_GETSKIN = 201;
            public const int IPC_GETSKINW = 1201;
            public const int IPC_EXECPLUG = 202;
            */
            public const int IPC_GETPLAYLISTFILE = 211;
            public const int IPC_GETPLAYLISTFILEW = 214;
            public const int IPC_GETPLAYLISTTITLE = 212;
            public const int IPC_GETPLAYLISTTITLEW = 213;
            /*
            public const int IPC_GETHTTPGETTER = 240;
            public const int IPC_GETHTTPGETTERW = 1240;
            public const int IPC_MBOPEN = 241;
            public const int IPC_CHANGECURRENTFILE = 245;
            public const int IPC_CHANGECURRENTFILEW = 1245;
            public const int IPC_GETMBURL = 246;
            public const int IPC_MBBLOCK = 248;
            public const int IPC_MBOPENREAL = 249;
            public const int IPC_ADJUST_OPTIONSMENUPOS = 280;
            public const int IPC_GET_HMENU = 281;
            public const int IPC_GET_EXTENDED_FILE_INFO = 290; //pass a pointer to the following struct in wParam
            public const int IPC_GET_EXTENDED_FILE_INFO_HOOKABLE = 296;
            public const int IPC_GET_BASIC_FILE_INFO = 291; //pass a pointer to the following struct in wParam
            public const int IPC_GET_BASIC_FILE_INFOW = 1291; //pass a pointer to the following struct in wParam
            public const int IPC_GET_EXTLIST = 292; //returns doublenull delimited. GlobalFree() it when done. if data is 0, returns raw extlist, if 1, returns something suitable for getopenfilename
            public const int IPC_GET_EXTLISTW = 1292; // wide char version of above
            public const int IPC_INFOBOX = 293;
            public const int IPC_INFOBOXW = 1293;
            public const int IPC_SET_EXTENDED_FILE_INFO = 294; //pass a pointer to the a extendedFileInfoStruct in wParam
            public const int IPC_WRITE_EXTENDED_FILE_INFO = 295;
            public const int IPC_FORMAT_TITLE = 297;
            public const int IPC_FORMAT_TITLE_EXTENDED = 298; // similiar to IPC_FORMAT_TITLE, but falls back to Winamp's %tags% if your passed tag function doesn't handle it
            public const int IPC_COPY_EXTENDED_FILE_INFO = 299;
            public const int IPC_COPY_EXTENDED_FILE_INFOW = 1299;
            public const int IPC_GETUNCOMPRESSINTERFACE = 331;
            public const int IPC_ADD_PREFS_DLG = 332;
            public const int IPC_ADD_PREFS_DLGW = 1332;
            public const int IPC_REMOVE_PREFS_DLG = 333;
            public const int IPC_OPENPREFSTOPAGE = 380;
            public const int IPC_GETINIFILE = 334;
            public const int IPC_GETINIDIRECTORY = 335;
            public const int IPC_GETPLUGINDIRECTORY = 336;
            public const int IPC_GETM3UDIRECTORY = 337;
            public const int IPC_GETM3UDIRECTORYW = 338;
            public const int IPC_SPAWNBUTTONPOPUP = 361;
            public const int IPC_OPENURLBOX = 360;
            public const int IPC_OPENFILEBOX = 362;
            public const int IPC_OPENDIRBOX = 363;
            public const int IPC_SETDIALOGBOXPARENT = 364;
            public const int IPC_GETDIALOGBOXPARENT = 365;
            public const int IPC_UPDATEDIALOGBOXPARENT = 366;
            public const int IPC_DRO_MIN = 401;
            public const int IPC_SET_JTF_COMPARATOR = 409;
            public const int IPC_SET_JTF_COMPARATOR_W = 410;
            public const int IPC_SET_JTF_DRAWTEXT = 416;
            public const int IPC_DRO_MAX = 499;
            public const int IPC_GET_GENSKINBITMAP = 503;
            public const int IPC_GET_EMBEDIF = 505;
            public const int IPC_SKINWINDOW = 534;
            public const int IPC_EMBED_ENUM = 532;
            public const int IPC_EMBED_ISVALID = 533;
            public const int IPC_CONVERTFILE = 506;
            public const int IPC_CONVERTFILEW = 515;
            public const int IPC_CONVERTFILE_END = 507;
            public const int IPC_CONVERTFILEW_END = 516;
            public const int IPC_CONVERT_CONFIG = 508;
            public const int IPC_CONVERT_CONFIG_END = 509;
            public const int IPC_CONVERT_CONFIG_ENUMFMTS = 510;
            public const int IPC_BURN_CD = 511;
            public const int IPC_CONVERT_SET_PRIORITY = 512;
            public const int IPC_CONVERT_SET_PRIORITYW = 517;
            public const int IPC_CONVERT_CONFIG_SET_ITEM = 513; // returns TRUE if successful
            public const int IPC_CONVERT_CONFIG_GET_ITEM = 514; // returns TRUE if successful
            public const int IPC_HOOK_TITLES = 850;
            public const int IPC_HOOK_TITLESW = 851;
            public const int IPC_GETSADATAFUNC = 800;
            public const int IPC_GETVUDATAFUNC = 801;
            public const int IPC_ISMAINWNDVISIBLE = 900;
            public const int IPC_SETPLEDITCOLORS = 920;
            public const int IPC_SPAWNEQPRESETMENU = 933;
            public const int IPC_SPAWNFILEMENU = 934; //menubar
            public const int IPC_SPAWNOPTIONSMENU = 935; //menubar
            public const int IPC_SPAWNWINDOWSMENU = 936; //menubar
            public const int IPC_SPAWNHELPMENU = 937; //menubar
            public const int IPC_SPAWNPLAYMENU = 938; //menubar
            public const int IPC_SPAWNPEFILEMENU = 939; //menubar
            public const int IPC_SPAWNPEPLAYLISTMENU = 940; //menubar
            public const int IPC_SPAWNPESORTMENU = 941; //menubar
            public const int IPC_SPAWNPEHELPMENU = 942; //menubar
            public const int IPC_SPAWNMLFILEMENU = 943; //menubar
            public const int IPC_SPAWNMLVIEWMENU = 944; //menubar
            public const int IPC_SPAWNMLHELPMENU = 945; //menubar
            public const int IPC_SPAWNPELISTOFPLAYLISTS = 946;
            public const int WM_WA_SYSTRAY = WM_USER + 1;
            public const int WM_WA_MPEG_EOF = WM_USER + 2;
            public const int IPC_IS_PLAYING_VIDEO = 501; // returns >1 if playing, 0 if not, 1 if old version (so who knows):)
            public const int IPC_GET_IVIDEOOUTPUT = 500; // see below for IVideoOutput interface
            public const int VIDUSER_SET_INFOSTRING = 0x1000;
            public const int VIDUSER_GET_VIDEOHWND = 0x1001;
            public const int VIDUSER_SET_VFLIP = 0x1002;
            public const int VIDUSER_SET_TRACKSELINTERFACE = 0x1003; // give your ITrackSelector interface as param2
            public const int VIDUSER_OPENVIDEORENDERER = 0x1004;
            public const int VIDUSER_CLOSEVIDEORENDERER = 0x1005;
            public const int VIDUSER_GETPOPUPMENU = 0x1006;
            public const int VIDUSER_SET_INFOSTRINGW = 0x1007;
            public const int IPC_CB_WND_EQ = 0; // use one of these for the param
            public const int IPC_CB_WND_PE = 1;
            public const int IPC_CB_WND_MB = 2;
            public const int IPC_CB_WND_VIDEO = 3;
            public const int IPC_CB_WND_MAIN = 4;
            public const int IPC_CB_ONSHOWWND = 600;
            public const int IPC_CB_ONHIDEWND = 601;
            public const int IPC_CB_GETTOOLTIP = 602;
            public const int IPC_CB_MISC = 603;
            public const int IPC_CB_CONVERT_STATUS = 604; // param value goes from 0 to 100 (percent)
            public const int IPC_CB_CONVERT_DONE = 605;
            public const int IPC_ADJUST_FFWINDOWSMENUPOS = 606;
            public const int IPC_ISDOUBLESIZE = 608;
            public const int IPC_ADJUST_FFOPTIONSMENUPOS = 609;
            public const int IPC_GETTIMEDISPLAYMODE = 610;
            public const int IPC_SETVISWND = 611;
            public const int ID_VIS_NEXT = 40382;
            public const int ID_VIS_PREV = 40383;
            public const int ID_VIS_RANDOM = 40384;
            public const int ID_VIS_FS = 40389;
            public const int ID_VIS_CFG = 40390;
            public const int ID_VIS_MENU = 40391;
            public const int IPC_GETVISWND = 612;
            public const int IPC_ISVISRUNNING = 613;
            public const int IPC_CB_VISRANDOM = 628; // param is status of random
            public const int IPC_SETIDEALVIDEOSIZE = 614;
            public const int IPC_GETSTOPONVIDEOCLOSE = 615;
            public const int IPC_SETSTOPONVIDEOCLOSE = 616;
            public const int IPC_TRANSLATEACCELERATOR = 617;
            public const int IPC_CB_ONTOGGLEAOT = 618;
            public const int IPC_GETPREFSWND = 619;
            public const int IPC_SET_PE_WIDTHHEIGHT = 620;
            public const int IPC_GETLANGUAGEPACKINSTANCE = 621;
            public const int LANG_IDENT_STR = 0;
            public const int LANG_LANG_CODE = 1;
            public const int LANG_COUNTRY_CODE = 2;
            public const int IPC_CB_PEINFOTEXT = 622; // data is a string, ie: "04:21/45:02"
            public const int IPC_CB_OUTPUTCHANGED = 623; // output plugin was changed in config
            public const int IPC_GETOUTPUTPLUGIN = 625;
            public const int IPC_SETDRAWBORDERS = 626;
            public const int IPC_DISABLESKINCURSORS = 627;
            public const int IPC_GETSKINCURSORS = 628;
            public const int IPC_CB_RESETFONT = 629;
            public const int IPC_IS_FULLSCREEN = 630;
            public const int IPC_SET_VIS_FS_FLAG = 631;
            public const int IPC_SHOW_NOTIFICATION = 632;
            public const int IPC_GETSKININFO = 633;
            public const int IPC_GETSKININFOW = 1633;
            */
            public const int IPC_GET_MANUALPLADVANCE = 634;
            public const int IPC_SET_MANUALPLADVANCE = 635;
            /*
            public const int IPC_GET_NEXT_PLITEM = 636;
            public const int IPC_GET_PREVIOUS_PLITEM = 637;
            public const int IPC_IS_WNDSHADE = 638;
            public const int IPC_SETRATING = 639;
            public const int IPC_GETRATING = 640;
            public const int IPC_GETNUMAUDIOTRACKS = 641;
            public const int IPC_GETNUMVIDEOTRACKS = 642;
            public const int IPC_GETAUDIOTRACK = 643;
            public const int IPC_GETVIDEOTRACK = 644;
            public const int IPC_SETAUDIOTRACK = 645;
            public const int IPC_SETVIDEOTRACK = 646;
            public const int IPC_PUSH_DISABLE_EXIT = 647;
            public const int IPC_POP_DISABLE_EXIT = 648;
            public const int IPC_IS_EXIT_ENABLED = 649;
            public const int IPC_IS_AOT = 650;
            public const int IPC_USES_RECYCLEBIN = 651;
            public const int IPC_FLUSHAUDITS = 652;
            public const int IPC_GETPLAYITEM_START = 653;
            public const int IPC_GETPLAYITEM_END = 654;
            public const int IPC_GETVIDEORESIZE = 655;
            public const int IPC_SETVIDEORESIZE = 656;
            public const int IPC_INITIAL_SHOW_STATE = 657;
            public const int IPC_PLCMD = 1000;
            public const int PLCMD_ADD = 0;
            public const int PLCMD_REM = 1;
            public const int PLCMD_SEL = 2;
            public const int PLCMD_MISC = 3;
            public const int PLCMD_LIST = 4;
            public const int MBCMD_BACK = 0;
            public const int MBCMD_FORWARD = 1;
            public const int MBCMD_STOP = 2;
            public const int MBCMD_RELOAD = 3;
            public const int MBCMD_MISC = 4;
            public const int IPC_VIDCMD = 1002;
            public const int VIDCMD_FULLSCREEN = 0;
            public const int VIDCMD_1X = 1;
            public const int VIDCMD_2X = 2;
            public const int VIDCMD_LIB = 3;
            public const int VIDPOPUP_MISC = 4;
            public const int IPC_STATS_LIBRARY_ITEMCNT = 1300; // updates library count status
            public const int IPC_FF_FIRST = 2000;
            public const int IPC_FF_COLOURTHEME_CHANGE = IPC_FF_ONCOLORTHEMECHANGED;
            public const int IPC_FF_ONCOLORTHEMECHANGED = IPC_FF_FIRST + 3;
            public const int IPC_FF_ISMAINWND = IPC_FF_FIRST + 4;
            public const int IPC_FF_GETCONTENTWND = IPC_FF_FIRST + 5;
            public const int IPC_FF_NOTIFYHOTKEY = IPC_FF_FIRST + 6;
            public const int IPC_FF_LAST = 3000;
            public const int IPC_GETDROPTARGET = 3001;
            public const int IPC_PLAYLIST_MODIFIED = 3002;
            public const int IPC_PLAYING_FILE = 3003;
            public const int IPC_PLAYING_FILEW = 13003;
            public const int IPC_FILE_TAG_MAY_HAVE_UPDATED = 3004;
            public const int IPC_FILE_TAG_MAY_HAVE_UPDATEDW = 3005;
            public const int IPC_ALLOW_PLAYTRACKING = 3007;
            public const int IPC_HOOK_OKTOQUIT = 3010;
            public const int IPC_WRITECONFIG = 3011;
            public const int IPC_UPDATE_URL = 3012;
            public const int IPC_GET_RANDFUNC = 3015; // returns a function to get a random number
            public const int IPC_METADATA_CHANGED = 3017;
            public const int IPC_SKIN_CHANGED = 3018;
            public const int IPC_REGISTER_LOWORD_COMMAND = 3019;
            public const int IPC_GET_DISPATCH_OBJECT = 3020;  // gets winamp main IDispatch * (for embedded webpages)
            public const int IPC_GET_UNIQUE_DISPATCH_ID = 3021; // gives you a unique dispatch ID that won't conflict with anything in winamp's IDispatch *
            public const int IPC_ADD_DISPATCH_OBJECT = 3022; // add your own dispatch object into winamp's.  This lets embedded webpages access your functions
            public const int IPC_GET_PROXY_STRING = 3023;
            public const int IPC_USE_REGISTRY = 3024;
            public const int IPC_GET_API_SERVICE = 3025;
            public const int IPC_GET_EXTENDED_FILE_INFOW = 3026;
            public const int IPC_GET_EXTENDED_FILE_INFOW_HOOKABLE = 3027;
            public const int IPC_SET_EXTENDED_FILE_INFOW = 3028;
            public const int IPC_PLAYLIST_GET_NEXT_SELECTED = 3029;
            public const int IPC_PLAYLIST_GET_SELECTED_COUNT = 3030;
            public const int IPC_GET_PLAYING_FILENAME = 3031;
            public const int IPC_OPEN_URL = 3032;
            public const int IPC_USE_UXTHEME_FUNC = 3033;
            public const int IPC_GET_PLAYING_TITLE = 3034;
            public const int IPC_CANPLAY = 3035;
            public const int IPC_FETCH_ALBUMART = 3036;
            public const int IPC_JSAPI2_GET_DISPATCH_OBJECT = 3037;
            public const int IPC_REGISTER_WINAMP_IPCMESSAGE = 65536;
            */
        }
    }
}
